config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  validates :name, presence: true, uniqueness: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :group
  belongs_to :user

  validates :content, presence: true, unless: :image?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]

  def index
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

def update
  if @group.update(group_params)
    redirect_to group_messages_path(@group), notice: 'グループを編集しました'
  else
    render :edit
  end
end

private

def group_params
  params.require(:group).permit(:name, { :user_ids => [] })
end

def set_group
  @group = Group.find(params[:id])
end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      redirect_to group_messages_path(@group), notice: 'メッセージが送信されました'
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  
  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right
      / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
      = f.collection_check_boxes :user_ids, User.all, :id, :name
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.wrapper

  = render 'shared/side_bar'

app/views/groups/index.jtml.haml
.wrapper

  = render 'shared/side_bar'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render 'form', { group: @group }

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/messages/index.html.haml
.flash-box
.wrapper
  .chat-side
    .side-header
      .side-header__box
        .side-header__box__user-name
          iii
        .side-header__box__menu
          .side-header__box__menu__new-group
            %a{:href => "#"}
          .side-header__box__menu__edit-user
            %i.fa.fa-edit
            %a{:href => "#"}
            %i.fa.fa-cog
    .groups
      .group
        .group__name
          test
        .group__message
          hello!
      .group
        .group__name
          sample-group
        .group__message
          hello!
      .group
        .group__name
          example
        .group__message
          まだメッセージはありません
  .chat
    .header
      .left-header
        .left-header__title
          chat
        %ul.left-header__members
          Member :
          %li.main-header__left-box__member-list
            aiueo
          %li.main-header__left-box__member-list
            kkkkkk
      .group-edit
        Edit
    .messages
      = render @messages
      .message__upper-info
        .message__upper-info__talker
          test-user
        .message__upper-info__date
          2019/09/20(Fri) 16:09:15
      .message__text__content
        メッセージ
      .message__upper-info
        .message__upper-info__talker
          test-user
        .message__upper-info__date
          2019/09/20(Fri) 16:09:15
      .message__text__content
        メッセージ
      .message__upper-info
        .message__upper-info__talker
          test-user
        .message__upper-info__date
          2019/09/20(Fri) 16:09:15
      .message__text__content
        メッセージ
    .form
      = form_for [@group, @message] do |f|
        = f.text_field :content, class: 'form__message' , placeholder: 'type a message'
        .form__mask
          = f.label :image, class: 'form__mask__image' %do
            = fa_icon 'picture-o' , class: 'icon'
            = f.file_field :image, class: 'hidden'
        = f.submit 'Send' , class: 'form__submit'
        -# %input.form__message{:name => "message[content]", :placeholder => "type a message", :type => "text"}/
        -# .form__new
        -#   %label.form__new__image
        -#     = fa_icon 'picture-o', class: 'icon'
        -#     %input.hidden{type: 'file'}
        -# %input.form__submit{type: 'submit', value: 'Send'}

app/views/shared/_side_bar.html.haml
.side-bar
  .header
    %h3.header__name
      name
    %ul.header__lists
      %li.list
        = link_to new_group_path do
          = fa_icon 'pencil-square-o', class: 'icon'
      %li.list
        = link_to "#" do
          = fa_icon 'cog', class: 'icon'
  -# .groups
  -#   a
  -#   - current_user.groups.each do |group|
  -#     .group
  -#       = link_to group_messages_path(group) do
  -#         .group__name
  -#           = group.name
  -#         .group__message
  -#           メッセージはまだありません。

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", '#', class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'